name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd rag-project-aws
            git pull origin main

            source venv/bin/activate

            export OPENSEARCH_HOST=${{ secrets.OPENSEARCH_HOST }}
            export AWS_REGION=${{ secrets.AWS_REGION }}
            
            pip install -r requirements.txt

            # kill anciens process
            pkill -f uvicorn || true
            pkill -f streamlit || true

            # relancer API
            nohup python -m uvicorn app.main:app --host 0.0.0.0 --port 8000 &

            # relancer Streamlit
            nohup streamlit run ui/streamlit_app.py --server.port 8501 &

            exit
          EOF